// Site behaviours — generated by GalSol
(function(){
  // scroll reveal
  var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}});},{threshold:.12,rootMargin:'0px 0px -8% 0px'});
  document.querySelectorAll('.reveal').forEach(function(el){io.observe(el);});

  // mobile nav
  document.querySelectorAll('[data-burger]').forEach(function(b){
    b.addEventListener('click',function(){var n=b.closest('[data-nav]');if(n)n.classList.toggle('open');});
  });
  document.querySelectorAll('[data-nav] .nav-links a').forEach(function(a){
    a.addEventListener('click',function(){var n=a.closest('[data-nav]');if(n)n.classList.remove('open');});
  });

  // countdowns
  document.querySelectorAll('[data-countdown]').forEach(function(cd){
    var target=new Date(cd.getAttribute('data-countdown')).getTime();
    if(isNaN(target))return;
    function pad(v){return (v<10?'0':'')+v;}
    function set(k,v){var el=cd.querySelector('[data-cd="'+k+'"]');if(el)el.textContent=pad(v);}
    function tick(){
      var d=target-Date.now();if(d<0)d=0;
      set('days',Math.floor(d/864e5));
      set('hours',Math.floor(d%864e5/36e5));
      set('mins',Math.floor(d%36e5/6e4));
      set('secs',Math.floor(d%6e4/1e3));
    }
    tick();setInterval(tick,1000);
  });
})();
