// Site behaviours — generated by GalSol
(function(){
  // scroll reveal
  var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}});},{threshold:.12,rootMargin:'0px 0px -8% 0px'});
  document.querySelectorAll('.reveal').forEach(function(el){io.observe(el);});

  // mobile nav
  document.querySelectorAll('[data-burger]').forEach(function(b){
    b.addEventListener('click',function(){var n=b.closest('[data-nav]');if(n)n.classList.toggle('open');});
  });
  document.querySelectorAll('[data-nav] .nav-links a').forEach(function(a){
    a.addEventListener('click',function(){var n=a.closest('[data-nav]');if(n)n.classList.remove('open');});
  });

  // Floating animated hearts canvas background
  var canvas = document.getElementById('heartsCanvas');
  if (canvas) {
    var ctx = canvas.getContext('2d');
    var hearts = [];
    
    function resize() {
      canvas.width = canvas.parentElement.offsetWidth;
      canvas.height = canvas.parentElement.offsetHeight;
    }
    window.addEventListener('resize', resize);
    resize();

    function createHeart() {
      return {
        x: Math.random() * canvas.width,
        y: canvas.height + 20,
        size: Math.random() * 15 + 8,
        speed: Math.random() * 1.5 + 0.6,
        opacity: Math.random() * 0.5 + 0.2,
        wobble: Math.random() * 2,
        wobbleSpeed: Math.random() * 0.02 + 0.01
      };
    }

    function drawHeart(ctx, x, y, size) {
      ctx.beginPath();
      ctx.moveTo(x, y + size / 4);
      ctx.quadraticCurveTo(x, y, x + size / 2, y);
      ctx.quadraticCurveTo(x + size, y, x + size, y + size / 3);
      ctx.quadraticCurveTo(x + size, y + (size * 2) / 3, x + size / 2, y + size);
      ctx.quadraticCurveTo(x, y + (size * 2) / 3, x, y + size / 3);
      ctx.quadraticCurveTo(x, y, x, y + size / 4);
      ctx.closePath();
      ctx.fill();
    }

    for (var i = 0; i < 25; i++) {
      hearts.push(createHeart());
      hearts[i].y = Math.random() * canvas.height;
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = 'rgba(255, 77, 121, 0.4)';
      
      for (var i = 0; i < hearts.length; i++) {
        var h = hearts[i];
        h.y -= h.speed;
        h.wobble += h.wobbleSpeed;
        var wobbleX = h.x + Math.sin(h.wobble) * 20;
        
        ctx.globalAlpha = h.opacity;
        drawHeart(ctx, wobbleX, h.y, h.size);
        
        if (h.y < -30) {
          hearts[i] = createHeart();
        }
      }
      ctx.globalAlpha = 1.0;
      requestAnimationFrame(animate);
    }
    animate();
  }

  // countdowns
  document.querySelectorAll('[data-countdown]').forEach(function(cd){
    var target=new Date(cd.getAttribute('data-countdown')).getTime();
    if(isNaN(target))return;
    function pad(v){return (v<10?'0':'')+v;}
    function set(k,v){var el=cd.querySelector('[data-cd="'+k+'"]');if(el)el.textContent=pad(v);}
    function tick(){
      var d=target-Date.now();if(d<0)d=0;
      set('days',Math.floor(d/864e5));
      set('hours',Math.floor(d%864e5/36e5));
      set('mins',Math.floor(d%36e5/6e4));
      set('secs',Math.floor(d%6e4/1e3));
    }
    tick();setInterval(tick,1000);
  });
})();
